---
title: "A simple SIR model with Ralget"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{A simple SIR model with Ralget}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```

```{r setup}
rm(list = ls())
library(tidyverse)
library(tidygraph)
library(ggraph)
library(patchwork)
library(magrittr)
library(ralget)
devtools::load_all()
prefix <- function(g, p){g %>% mutate(name = paste0(p,"_",name))}

migration_matrix <- 
function(to = c("I-Mi","I-Mj","I-Mk"), 
         from =c("I-1i","I-1j","I-1k"), 
         persistence, 
         migration){
# to = c("a_S02","b_S02")
# from = c("a_S03","b_S03")
# persistence = .95
# migration = .10 
 d1 <-  
    tidyr::crossing(l1 = to,l2=from) %>%
    mutate(comb = map2_chr(l1,l2, ~ sort(c(.x,.y)) %>% 
                paste(collapse ="")))  
 d1 %>% 
    mutate(migration = 
                ifelse(str_remove_all(l1,"[0-9]+")==str_remove_all(l2,"[0-9]+"),
                persistence, abs(rnorm(nrow(d1),.01,migration)))) %>%   
    group_by(l1) %>% 
    mutate(migration = migration / sum( migration)) %>%
    select(-comb) %>%
    mutate(vert = pmap(list(l1,l2,migration),
    function(l1,l2,migration){v(l1)*m(migration)*v(l2)}))
}

```

```{r}
product <- function(...){list(...) %>% reduce(`*`)}
m <- function(m){ e(.func = function(.value){.value * m})}
const <- function(x){function(...){x}}
increment_t <- function(g, t = 1){
  g %>% 
  mutate(name = 
    str_extract(name,"[0-9]+$") %>% as.numeric() %>% `+`(t) %>% 
    as.character() %>% str_pad(2,"left", "0") %>% 
    str_remove("NA") %>% 
    paste0(str_remove(name,"[0-9]+$"),.) %>% str_remove("NA"))
}
```



```{r}
# Initial conditions
S00 <- v("S00", .func = const(10000))
I00 <- v("I00", .func = const(100))
R00 <- v("R00", .func = const(0))
# First period states 
S01 <- v("S01", .func = sum)
I01 <- v("I01", .func = sum)
b_I01 <- v("b_I01", .func = sum)
R01 <- v("R01", .func = sum)
# Transition states 
BIS01 <- v("BIS01", .func = product)
GI01  <- v("GI01", .func = product)
# Second period
S02 <- v("S02", .func = sum)
I02 <- v("I02", .func = sum)
R02 <- v("R02", .func = sum)

S03 <- v("S03", .func = sum)
I03 <- v("I03", .func = sum)
R03 <- v("R03", .func = sum)
# Parameters 
B <- v("B", .func = const(.3/10010))
G <- v("G", .func = const(500/10010))
```


```{r echo=TRUE, message=FALSE, warning=FALSE, include = TRUE, fig.height=5, fig.width=7}
# Initial connections
SIR0 <-
S00 * m(1) * S01 + 
I00 * m(1) * I01 + 
R00 * m(1) * R01 

# SIR Dynamics 
SIR <- 
S01   * (m(1) * BIS01 + m(1)  * S02 ) +
I01   * (m(1) * BIS01 + m(1)  * I02 + m(1)*GI01 )  +
R01   * (m(1) * R02                 )  +
BIS01 * (m(-1) * S02   + m(1)  * I02 ) + 
GI01  * (m(-1) * I02   + m(1) *  R02 )  +
B     * (m(1) * BIS01) +
G     * (m(1) * GI01) +
S03 + I03 + R03

SIR01 <- SIR0 + SIR
SIR01 <- map(letters[1:2],~ prefix(SIR0 + SIR, .x)) %>% reduce(`+`) 
SIR03 <- map(letters[1:2],~ prefix(SIR, .x)) %>% reduce(`+`) 

mig_s <- migration_matrix(c("a_S02","b_S02"),c("a_S03","b_S03"), .55,.001) %>% 
         pull(vert) %>% reduce(`+`) %>%
         mutate(.attrs = map(1,~ list(.func = sum)))


mig_i <- migration_matrix(c("a_I02","b_I02"),c("a_I03","b_I03"), .95,.10) %>% 
         pull(vert) %>% reduce(`+`) %>%
         mutate(.attrs = map(1,~ list(.func = sum)))

mig_r <- migration_matrix(c("a_R02","b_R02"),c("a_R03","b_R03"), .95,.10) %>% 
         pull(vert) %>% reduce(`+`) %>%
         mutate(.attrs = map(1,~ list(.func = sum)))

sirtm <- SIR01 + mig_s + mig_i + mig_r
plot(sirtm) 

sirt <- SIR03 + mig_s + mig_i + mig_r
sirt2 <- map(seq(2,100,2),increment_t, g = sirt) %>% reduce(`+`)

i00n <- v("i00", .func = const(-100)) * m(1) * b_I01 

sirt_f <- sirtm + sirt2 + i00n
# plot(sirt_f)
sirtm_p <- sirt_f %>% get_edge_names() %>% activate("nodes") %>% evaluate_prepare()  

result <- 
sirtm_p %>% get_edge_names() %>% activate("nodes") %>% evaluate_execute() 


```

```{r echo=TRUE, message=FALSE, warning=FALSE, include = TRUE, fig.height=5, fig.width=7}
## Extract Data
A <- 
result %>%
mutate(r = map_dbl(eval_statement, ~ .x)) %>% 
as_tibble() %>% 
select(name, r) %>% 
mutate(t = str_extract(name, "[0-9]+")) %>% 
mutate(name = str_remove(name, "[0-9]+")) %>% 
spread(name,r)

## Plot
A %>% gather(key,value, -t) %>% 
  mutate(city = str_extract(key,"[a-z]")) %>%
  mutate(key = str_remove(key,"[a-z]_")) %>%
ggplot(aes(x = as.numeric(t),y = value, color = key )) + 
geom_line() + 
geom_point() + facet_wrap(~city)
```


```{r echo=TRUE, message=FALSE, warning=FALSE, include = TRUE, fig.height=6, fig.width=14.5}
# Connect 150 cycles end to end
S01
S02

S01i <- map(letters[1:3],~ v(paste0("S0",.x))) %>% reduce(`+`)
S02i <- map(letters[1:3],~ v(paste0("S1",.x))) %>% reduce(`+`)

S <- S01i*S02i
class(S) <- class(S)[-1]
plot(S)

crossing(l1 = letters[1:3],l2 = letters[1:3]) %>%
mutate(comb = map2_chr(l1,l2, ~ sort(c(.x,.y)) %>% 
              paste(collapse =""))) %>% 
mutate(migration = ifelse(l1==l2,.95, abs(rnorm(nrow(.),.01,.10)))) %>%   
group_by(l1) %>% 
mutate(migration = migration / sum( migration)) %>%
select(-comb) %>% spread(l1,migration)



mig_m <- migration_matrix(c("a_S02","b_S02"),c("a_S03","b_S03"), .95,.10) %>% 
         pull(vert) %>% reduce(`+`)


plot(mig_m)
letters[1:3] %>% map(~ .x %>% paste0(letters[1:3])) %>% unlist()

S %>% get_edge_names() %>%
mutate(change = )

```
















