---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ralget

<!-- badges: start -->
<!-- badges: end -->

The goal of ralget is to ...

## Installation

You can install the released version of ralget from [CRAN](https://CRAN.R-project.org) with:

``` r
install.packages("ralget")
```

And the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("ianmoran11/ralget")
```
## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(tidyverse)
library(tidygraph)
library(tibble)
library(ggraph)
library(magrittr)
library(ralget)
devtools::load_all()

# Algebra ----------------------------------------------------------------------
## Basic replication -----------------------------------------------------------
p <- v("p"); q <- v("q"); s <- v("s"); r <- v("r"); 

g1 <- p*q+s
g2 <- q*s+q*r

g1 %>% plot
g2 %>% plot
(g1+g2) %>% plot()

g3 <- s*r
g3 %>% plot()
(g1*g3) %>% plot()

```
